### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by CapsCoder** [acidvegas/acid-drop#2]
All I get is a black screen. Do you know why?

**Comment by acidvegas** [comment]
Does this compile without any issues for you?

You are using VS code to flash it?

**Comment by CapsCoder** [comment]
> Does this compile without any issues for you?
> 
> 
> 
> You are using VS code to flash it?

Yes I am using VSCode to flash it

**Comment by acidvegas** [comment]
~~Ok........well you really aren't giving me any details to debug this situation so I don't know how you expect to get help. Compiles and flashes fine for me. Be more descriptive in what you did and tried next time.~~

@CapsCoder turns out I needed to specify the version of esppressifs platform in platormio.ini.

The issue has been fixed now. Sorry about all that.
